### PR TITLE
OSRA-356: Partner's province shouldn't be editable

### PR DESCRIPTION
**Pull request by motasem-salem**
https://osraav.atlassian.net/browse/OSRA-356

### CODE REVIEW

**Comment by theB264** [comment]
Should we put a test for this in the spec or is this considered eye-candy because the model rejects updating this? related: https://github.com/AgileVentures/osra/pull/213

**Comment by motasem-salem** [comment]
In AA, we tested this in a feature. I assumed it will be the same in this case.

**Comment by theB264** [comment]
I'm also struggling trying to get a feature written before https://github.com/AgileVentures/osra/pull/261 is merged.

**Comment by PurityControl** [comment]
I'm okay with this

**Comment by NikitaAvvakumov** [comment]
Do you think a view spec would be more appropriate here? We didn't have the option of writing those for AA but can for HQ. A feature seems to be overkill to test the behaviour of logic within a single view. I'd prefer to limit features to high-level exercises that ensure that multiple parts of the app function together.

**Comment by PurityControl** [comment]
Given this is a flourish rather than a functionality issue I'm not sure it warrants a test. We probably wouldn't put this in a test if it was part of the original feature.

**Comment by theB264** [comment]
I'm okay either way

**Pull request merged**
