### PR TITLE
Display pagination for User's sponsors

### PR DESCRIPTION
**Pull request by Maroo-b**
- display pagination for attached sponsors
- add helper for passing custom pagination param
- Add feature test to check the pagination of two objects in same page

### CODE REVIEW

**Comment by b264** [comment]
screenshot from 2016-12-02 11 23 37

**Comment by Maroo-b** [comment]
@b264 thanks for the review, I did update the PR to change the helper method as recommended.

**Comment by b264** [comment]
:shipit:

**Comment by b264** [comment]
OSRA-449

**Pull request merged**
