### PR TITLE
osra420: Sponsor table header sort

### PR DESCRIPTION
**Pull request by razorcd**
https://osraav.atlassian.net/browse/OSRA-420

Added class method `custom_sort` on Sponsor using a reusable concern
Added a clean chain of `Sponsor.filter.column_sort.paginate` to controller
Changed Sponsor index table headers to use links for sorting by column
Refactored `.where_with_conditions` to allow chaining even on empty arguments
Created partial `_sortable_table_header_link.html.erb` for adding sortable table header links
Added integration tests for sponsor index table

### CODE REVIEW

**Comment by razorcd** [comment]
sorting sponsors#index table is ready for reviewing

**Comment by razorcd** [comment]
sort

**Comment by gmunumel** [comment]
Looks amazing. Excelent work :+1:

**Comment by razorcd** [comment]
Could you please fetch this branch and try it on your local machine? Maybe you find a bug :)

**Comment by gmunumel** [comment]
Sure. I will do that :+1:

**Comment by gmunumel** [comment]
It runs good. Without problem. 

Do you have production data that I can use to populate my db?

**Comment by razorcd** [comment]
production data no, populating the db with our factories is enough
thanks

**Pull request merged**
