### PR TITLE
OSRA-389 OSRA-390 father_alive -> father_deceased

### PR DESCRIPTION
**Pull request by NikitaAvvakumov**
https://osraav.atlassian.net/browse/OSRA-389
https://osraav.atlassian.net/browse/OSRA-390

Replace `father_alive` in the Orphan model with `father_deceased` to match
OSRA spreadsheets.

 - add new boolean column `father_deceased` to orphans table and populate it
 with the inverse values of existing `father_alive`; remove `father_alive`
 column
 - rename `father_alive` to `father_deceased` in the pending_orphans table
 - modify importer settings to process column G of spreadsheets as
 `father_deceased` instead of `father_alive` and to use "Y" & "N" only
 (not Arabic words for 'dead' & 'alive')
 - refactor orphan validations pertaining to father's death for clarity and to
 use `father_deceased` as the main point of reference
 - switch from using `father_alive` to `father_deceased` in models, tests,
 views, etc.
 - restore orphans factory's ability to randomly produce orphans with living or
 deceased fathers
 - update spreadsheet fixtures to follow latest template format and to have
 info consistent with new usage of `father_deceased`

### CODE REVIEW

**Comment by razorcd** [comment]
can you send me a copy of the production db? I would like to test this PR

**Comment by NikitaAvvakumov** [comment]
@razorcd PM sent on Slack

**Comment by gmunumel** [comment]
What is the plan B in case we get a problem in production?

**Comment by NikitaAvvakumov** [comment]
@gmunumel Roll back the commits, restore db from backup. Painful but doable.

**Comment by gmunumel** [comment]
I guess you are going to try to apply this change at midnight.

**Comment by NikitaAvvakumov** [comment]
Yes, we have access to the production db, so we can make sure that all orphan records are still valid after the update. @razorcd ran this against a copy of the production db last night and everything looked fine. Let's be very confident in our code before merging, that way we won't have to keep our finger on the 'Alarm' button as we push to production :)

**Comment by gmunumel** [comment]
hahaha, yes. :D

**Comment by razorcd** [comment]
:shipit:

**Comment by gmunumel** [comment]
Ready to go :+1:

**Pull request merged**
