### PR TITLE
Osra 403 Add "View All", "View Sponsored", "View Unsponsored" filter to orphans#index [WIP]

### PR DESCRIPTION
**Pull request by ZmagoD**
Add "View All", "View Sponsored", "View Unsponsored" filter to orphans#index

### CODE REVIEW

**Comment by razorcd** [comment]
something is wrong here with the commits.  
Does it need a rebase or is this branch merged with `develop`?

**Comment by razorcd** [comment]
lets talk about this feature in the scrum, tonight

**Comment by robbiejackson** [comment]
There's a lot of duplication with the different partials here (not following the DRY principle). 
It would be better to have a single partial where the condition to apply to the orphans is passed in as a parameter (eg set up something in the locals: of the partial).

**Comment by ZmagoD** [comment]
Ok thanks for the tip

**Comment by gmunumel** [comment]
You are missing the tests for the views, helpers and models.

**Comment by gmunumel** [comment]
There is a merge conflict. Checkout the develop branch and rebase your branch. If you don't know how to do it ask us.

**Comment by ZmagoD** [comment]
Ok I will check out!

**Pull request closed without merging**
