### PR TITLE
OSRA415 - orphans#index Filters

### PR DESCRIPTION
**Pull request by gmunumel**
https://osraav.atlassian.net/browse/OSRA-415

### CODE REVIEW

**Comment by gmunumel** [comment]
screenshot from 2015-05-26 19 39 32

**Comment by razorcd** [comment]
please update the PR with the tests so I can take a look as discussed in last scrum. If still needed.

**Comment by gmunumel** [comment]
Added the tests. They are failling. 

I've tested the functionality, the only field that is not working is `original_address_city` because I need to do a joins between `orphans` and `address` but I don't see how to do it. 

When I get the above done I'm going to make progress with the failling tests.

**Comment by razorcd** [comment]
@gmunumel please review/merge:  https://github.com/gmunumel/osra/pull/3

**Pull request merged**
